//! Safe Rust wrapper around VPP's stats-segment client C API
//! (`stat_client.h`), the shared-memory IPC mechanism VPP's own
//! `vpp_prometheus_export` tool uses to read VPP's Prometheus-style
//! counters.
//!
//! The raw FFI bindings (generated by `build.rs` via bindgen, scoped to just
//! the handful of `stat_segment_*` symbols this crate needs) live in the
//! private [`bindings`] module. Everything in this file copies data out of
//! VPP-owned shared memory into owned Rust types before returning it, so
//! nothing here carries a lifetime tied to the C side.

mod bindings;

use bindings::*;
use std::ffi::{c_void, CStr, CString};
use std::fmt;
use std::sync::atomic::{AtomicBool, Ordering};
use std::sync::Once;

// `vac_mem_init` isn't part of stat_client.h's surface (it's declared in
// libvppapiclient's separate vac_* shared-memory-transport header), so it's
// hand-declared here rather than pulled in via this crate's bindgen pass -
// but it's exported by the same libvppapiclient.so this crate already links,
// so no new native dependency is introduced.
extern "C" {
    fn vac_mem_init(size: usize);
}

/// Every `stat_segment_*` call that builds a vector (`stat_segment_ls`,
/// `stat_segment_string_vector`, `stat_segment_dump`, ...) allocates from
/// vppinfra's clib heap (see `stat_client.c`'s use of `vec_add1`/
/// `vec_validate`). That heap does not exist until something calls
/// `clib_mem_init` - every VPP-supplied consumer of this API does so
/// explicitly (`vpp_prometheus_export.c`, `vpp_get_stats.c`) via
/// `clib_mem_init` directly or, as here, via libvppapiclient's
/// `vac_mem_init` wrapper around it. Without this, the first allocation
/// dereferences a NULL heap pointer and segfaults the whole process - not
/// just the calling thread, since this is a C-level SIGSEGV.
///
/// Guarded with `Once` because `clib_mem_init` sets a single process-wide
/// heap; calling it twice would orphan/corrupt whatever was already
/// allocated. This guard only protects calls made through this crate - the
/// sibling `vpp-api-transport` crate's `shmem::Transport::new()` also calls
/// `vac_mem_init(0)` unconditionally, with no shared guard. If a process
/// ever uses both a `StatClient` and a `vpp-api-transport` shmem
/// `Transport`, whichever initializes second will corrupt the heap the
/// first one is using. That combination isn't in use anywhere in this
/// workspace today (the only prior caller of the shmem transport was
/// removed), but this isn't process-wide-safe against it being reintroduced
/// without also coordinating the init between the two crates.
static CLIB_HEAP_INIT: Once = Once::new();

fn ensure_clib_heap_initialized() {
    CLIB_HEAP_INIT.call_once(|| unsafe { vac_mem_init(0) });
}

/// VPP's compiled-in default path for the stats-segment control socket
/// (`STAT_SEGMENT_SOCKET_FILE` in stat_client.h). Callers decide the actual
/// socket path to connect to; this is offered purely for convenience.
pub const DEFAULT_STAT_SEGMENT_SOCKET: &str = "/run/vpp/stats.sock";

/// A pattern that matches every entry in the stats directory tree - the
/// same "match everything" pattern production's `vpp_prometheus_export`
/// tool is invoked with (`ExecStart=/usr/bin/vpp_prometheus_export /`).
pub const MATCH_ALL_PATTERN: &str = "/";

/// How many times a `stat_segment_ls()`/`stat_segment_dump()` pair is
/// rebuilt before [`StatClient::dump`] gives up. `stat_segment_dump()`
/// returns NULL whenever the stats directory epoch moves between the
/// `ls()` and the `dump()`, which routine directory churn (e.g. a session
/// being added) is enough to cause, so one or two rebuilds are routine;
/// needing this many in a row means the box is churning the directory
/// faster than a dump can walk it.
const STAT_DUMP_RETRIES: u32 = 5;

/// Only one stats-segment connection can be open at a time: the C library
/// tracks connection state in a single process-wide global
/// (`stat_client_main`), not per-handle, so a second concurrent
/// [`StatClient::connect`] would silently share/clobber the first one's
/// state rather than opening an independent connection.
static CONNECTED: AtomicBool = AtomicBool::new(false);

/// Mirrors `stat_directory_type_t` from stat_client.h / vlib/stats/shared.h.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum StatDirType {
    Illegal,
    ScalarIndex,
    CounterVectorSimple,
    CounterVectorCombined,
    NameVector,
    Empty,
    Symlink,
    HistogramLog2,
    RingBuffer,
    Gauge,
    /// A directory-type value this crate doesn't recognize (e.g. a VPP
    /// version newer than the headers this crate was built against added
    /// a variant). Carries the raw value for diagnostics.
    Unknown(u32),
}

impl From<stat_directory_type_t> for StatDirType {
    // The bindgen-generated `stat_directory_type_t_STAT_DIR_TYPE_*` constants
    // mirror the C enumerator names verbatim, which trips Rust's
    // non-upper-case-globals lint even though they're already all-caps
    // (the mixed-case `stat_directory_type_t_` prefix bindgen adds is what
    // triggers it).
    #[allow(non_upper_case_globals)]
    fn from(raw: stat_directory_type_t) -> Self {
        match raw {
            stat_directory_type_t_STAT_DIR_TYPE_ILLEGAL => StatDirType::Illegal,
            stat_directory_type_t_STAT_DIR_TYPE_SCALAR_INDEX => StatDirType::ScalarIndex,
            stat_directory_type_t_STAT_DIR_TYPE_COUNTER_VECTOR_SIMPLE => {
                StatDirType::CounterVectorSimple
            }
            stat_directory_type_t_STAT_DIR_TYPE_COUNTER_VECTOR_COMBINED => {
                StatDirType::CounterVectorCombined
            }
            stat_directory_type_t_STAT_DIR_TYPE_NAME_VECTOR => StatDirType::NameVector,
            stat_directory_type_t_STAT_DIR_TYPE_EMPTY => StatDirType::Empty,
            stat_directory_type_t_STAT_DIR_TYPE_SYMLINK => StatDirType::Symlink,
            stat_directory_type_t_STAT_DIR_TYPE_HISTOGRAM_LOG2 => StatDirType::HistogramLog2,
            stat_directory_type_t_STAT_DIR_TYPE_RING_BUFFER => StatDirType::RingBuffer,
            stat_directory_type_t_STAT_DIR_TYPE_GAUGE => StatDirType::Gauge,
            other => StatDirType::Unknown(other),
        }
    }
}

/// A stat entry's owned, safe-Rust data, keyed by [`StatDirType`].
///
/// Simple counter vectors and combined counter vectors are indexed
/// `[thread][index]`, matching the C API's per-worker-thread layout.
/// `Unsupported` covers directory types this crate doesn't turn into owned
/// data (`Empty`, `Symlink`, `RingBuffer`, `Illegal`, and anything
/// unrecognized) - the caller still gets the entry's name and `StatDirType`
/// in [`StatEntry`].
#[derive(Debug, Clone, PartialEq)]
pub enum StatValue {
    Scalar(f64),
    SimpleCounterVec(Vec<Vec<u64>>),
    CombinedCounterVec(Vec<Vec<(u64, u64)>>),
    NameVector(Vec<String>),
    /// Per-thread log2-histogram bins (`[thread][bin]`), bin 0 holding the
    /// histogram's minimum exponent rather than a count - see
    /// `print_log2_histogram_metric` in VPP's `dump_metrics.c` for how the
    /// remaining bins are turned into cumulative Prometheus buckets.
    HistogramLog2Bins(Vec<Vec<u64>>),
    Unsupported,
}

/// One entry from the stats directory, with its data fully copied out of
/// VPP's shared memory.
#[derive(Debug, Clone, PartialEq)]
pub struct StatEntry {
    pub name: String,
    pub dir_type: StatDirType,
    pub via_symlink: bool,
    pub value: StatValue,
}

/// Errors returned by [`StatClient`].
#[derive(Debug)]
pub enum StatClientError {
    /// A [`StatClient`] is already connected in this process (see
    /// [`CONNECTED`]).
    AlreadyConnected,
    /// `stat_segment_connect()` returned this non-zero code.
    ConnectFailed(i32),
    /// `stat_segment_dump()` kept returning NULL (the stats directory
    /// epoch kept moving) across [`STAT_DUMP_RETRIES`] rebuilds of the
    /// index vector.
    DumpRetriesExhausted,
}

impl fmt::Display for StatClientError {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        match self {
            StatClientError::AlreadyConnected => {
                write!(f, "a stats-segment connection is already open in this process")
            }
            StatClientError::ConnectFailed(code) => {
                write!(f, "stat_segment_connect failed with code {}", code)
            }
            StatClientError::DumpRetriesExhausted => write!(
                f,
                "stats directory kept changing over {} attempts; giving up",
                STAT_DUMP_RETRIES
            ),
        }
    }
}

impl std::error::Error for StatClientError {}

/// A connection to a VPP stats-segment. Connects via
/// [`StatClient::connect`]; the connection is closed automatically on
/// `Drop`.
pub struct StatClient {
    connected: bool,
}

impl StatClient {
    /// Connect to the stats-segment socket at `socket_path` (e.g.
    /// [`DEFAULT_STAT_SEGMENT_SOCKET`]).
    pub fn connect(socket_path: &str) -> Result<Self, StatClientError> {
        if CONNECTED.swap(true, Ordering::SeqCst) {
            return Err(StatClientError::AlreadyConnected);
        }

        ensure_clib_heap_initialized();

        let c_path = CString::new(socket_path).expect("socket path contains a NUL byte");
        let rc = unsafe { stat_segment_connect(c_path.as_ptr()) };
        if rc != 0 {
            CONNECTED.store(false, Ordering::SeqCst);
            return Err(StatClientError::ConnectFailed(rc));
        }
        Ok(StatClient { connected: true })
    }

    /// Dump every stats-directory entry matching any of `patterns` into
    /// owned Rust data. Patterns are POSIX *basic* regexes (unanchored),
    /// per `stat_segment_ls()`'s contract in stat_client.h. Retries
    /// internally (see [`STAT_DUMP_RETRIES`]) if the directory epoch moves
    /// mid-dump, so callers don't have to.
    ///
    /// Takes `&mut self` even though nothing here touches `StatClient`'s own
    /// fields: the underlying C calls mutate global state (`stat_client_main`,
    /// per `stat_client.h`'s non-`_r` functions), so two calls on the same
    /// connection can never safely run concurrently. `&mut self` makes the
    /// borrow checker enforce that exclusivity - a shared `&self` would let
    /// safe code (e.g. an `Arc<StatClient>` cloned across tasks) trigger a
    /// real data race on that global state with no `unsafe` at the call
    /// site.
    pub fn dump(&mut self, patterns: &[&str]) -> Result<Vec<StatEntry>, StatClientError> {
        let pattern_vec = build_pattern_vec(patterns);
        let result = dump_pattern_vec(pattern_vec);
        free_pattern_vec(pattern_vec);
        result
    }

    /// Convenience wrapper around [`StatClient::dump`] for the common
    /// "walk the whole stats tree" case (equivalent to
    /// `dump(&[MATCH_ALL_PATTERN])`).
    pub fn dump_all(&mut self) -> Result<Vec<StatEntry>, StatClientError> {
        self.dump(&[MATCH_ALL_PATTERN])
    }
}

impl Drop for StatClient {
    fn drop(&mut self) {
        if self.connected {
            unsafe { stat_segment_disconnect() };
            self.connected = false;
            CONNECTED.store(false, Ordering::SeqCst);
        }
    }
}

/// Build a `uint8_t **` pattern vector via `stat_segment_string_vector()`,
/// the same helper `stat_segment_ls()`'s callers use to build the pattern
/// list.
fn build_pattern_vec(patterns: &[&str]) -> *mut *mut u8 {
    let mut vec_ptr: *mut *mut u8 = std::ptr::null_mut();
    for p in patterns {
        let c = CString::new(*p).expect("pattern contains a NUL byte");
        vec_ptr = unsafe { stat_segment_string_vector(vec_ptr, c.as_ptr()) };
    }
    vec_ptr
}

/// Free a pattern vector built by [`build_pattern_vec`]: every element is
/// itself a clib vector (a string) that needs freeing before the outer
/// vector of pointers does.
fn free_pattern_vec(vec_ptr: *mut *mut u8) {
    for entry in unsafe { copy_vpp_vec(vec_ptr) } {
        if !entry.is_null() {
            unsafe { stat_segment_vec_free(entry as *mut c_void) };
        }
    }
    if !vec_ptr.is_null() {
        unsafe { stat_segment_vec_free(vec_ptr as *mut c_void) };
    }
}

/// Dump `pattern_vec` with a retry loop for the epoch-change case:
/// `stat_segment_dump()` returns NULL whenever the stats directory epoch
/// moved between the `ls()` that built its index vector and the `dump()`
/// itself, so the index vector has to be rebuilt and the dump retried.
/// Bounded at [`STAT_DUMP_RETRIES`] attempts so sustained directory churn
/// can't wedge the caller forever.
fn dump_pattern_vec(pattern_vec: *mut *mut u8) -> Result<Vec<StatEntry>, StatClientError> {
    let mut stats = unsafe { stat_segment_ls(pattern_vec) };
    let mut res: *mut stat_segment_data_t = std::ptr::null_mut();

    for _ in 0..STAT_DUMP_RETRIES {
        res = unsafe { stat_segment_dump(stats) };
        if !res.is_null() {
            break;
        }
        unsafe { stat_segment_vec_free(stats as *mut c_void) };
        stats = unsafe { stat_segment_ls(pattern_vec) };
    }

    if res.is_null() {
        unsafe { stat_segment_vec_free(stats as *mut c_void) };
        return Err(StatClientError::DumpRetriesExhausted);
    }

    let entries = unsafe { copy_entries(res) };
    unsafe { stat_segment_data_free(res) };
    unsafe { stat_segment_vec_free(stats as *mut c_void) };

    Ok(entries)
}

/// Copy every `stat_segment_data_t` out of the vector `stat_segment_dump()`
/// returned, into owned [`StatEntry`] values, before the caller frees `res`
/// via `stat_segment_data_free()`.
///
/// # Safety
/// `res` must be a valid (possibly NULL/zero-length) clib vector of
/// `stat_segment_data_t`, as returned by `stat_segment_dump()`.
unsafe fn copy_entries(res: *mut stat_segment_data_t) -> Vec<StatEntry> {
    copy_vpp_vec(res)
        .into_iter()
        .map(|entry| {
            let name = if entry.name.is_null() {
                String::new()
            } else {
                CStr::from_ptr(entry.name).to_string_lossy().into_owned()
            };
            let dir_type = StatDirType::from(entry.type_);
            let value = copy_value(dir_type, &entry.__bindgen_anon_1);
            StatEntry {
                name,
                dir_type,
                via_symlink: entry.via_symlink,
                value,
            }
        })
        .collect()
}

/// Copy a `stat_segment_data_t`'s union payload into an owned [`StatValue`],
/// per `dir_type`.
///
/// # Safety
/// `data` must be the union payload of a `stat_segment_data_t` whose
/// `type` field is `dir_type` - the union member that's safe to read
/// depends entirely on that tag, exactly as in the C API.
unsafe fn copy_value(
    dir_type: StatDirType,
    data: &stat_segment_data_t__bindgen_ty_1,
) -> StatValue {
    match dir_type {
        StatDirType::ScalarIndex | StatDirType::Gauge => StatValue::Scalar(data.scalar_value),
        StatDirType::CounterVectorSimple => StatValue::SimpleCounterVec(
            copy_vpp_vec(data.simple_counter_vec)
                .into_iter()
                .map(|per_thread| copy_vpp_vec(per_thread))
                .collect(),
        ),
        StatDirType::CounterVectorCombined => StatValue::CombinedCounterVec(
            copy_vpp_vec(data.combined_counter_vec)
                .into_iter()
                .map(|per_thread| {
                    copy_vpp_vec(per_thread)
                        .into_iter()
                        .map(|c| (c.packets, c.bytes))
                        .collect()
                })
                .collect(),
        ),
        StatDirType::NameVector => StatValue::NameVector(
            copy_vpp_vec(data.name_vector)
                .into_iter()
                .map(|entry| {
                    if entry.is_null() {
                        String::new()
                    } else {
                        CStr::from_ptr(entry as *const std::os::raw::c_char)
                            .to_string_lossy()
                            .into_owned()
                    }
                })
                .collect(),
        ),
        StatDirType::HistogramLog2 => StatValue::HistogramLog2Bins(
            copy_vpp_vec(data.log2_histogram_bins)
                .into_iter()
                .map(|per_thread| copy_vpp_vec(per_thread))
                .collect(),
        ),
        StatDirType::Illegal
        | StatDirType::Empty
        | StatDirType::Symlink
        | StatDirType::RingBuffer
        | StatDirType::Unknown(_) => StatValue::Unsupported,
    }
}

/// Copy a clib vector (as used throughout the stats-segment API: a
/// possibly-NULL pointer whose length `stat_segment_vec_len()` reports) into
/// an owned `Vec<T>`. NULL is a valid, zero-length clib vector by
/// convention, so it maps to an empty `Vec` rather than being treated as an
/// error.
///
/// # Safety
/// `ptr` must either be NULL, or a valid clib vector of at least
/// `stat_segment_vec_len(ptr)` initialized, readable `T` values.
unsafe fn copy_vpp_vec<T: Copy>(ptr: *mut T) -> Vec<T> {
    if ptr.is_null() {
        return Vec::new();
    }
    let len = stat_segment_vec_len(ptr as *mut c_void).max(0) as usize;
    if len == 0 {
        return Vec::new();
    }
    std::slice::from_raw_parts(ptr as *const T, len).to_vec()
}
